#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// FORWARD DECLARATIONS


namespace BPW_MenuPause
{
	class UPLACEHOLDER_CLASS__BPW_RequestYesNo_C_2;
	class UPLACEHOLDER_CLASS__BPW_BtnSave_C_0;
}

namespace BPW_StartGame
{
	class UPLACEHOLDER_CLASS__BPW_BtnSave_C_0;
	class UPLACEHOLDER_CLASS__BPW_RequestYesNo_C_2;
}
