#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AreaFlat

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AreaFlat.AreaFlat_C
// 0x0000 (0x0048 - 0x0048)
class UAreaFlat_C final : public UNavArea_Door
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AreaFlat_C">();
	}
	static class UAreaFlat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAreaFlat_C>();
	}
};

}

