#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AudioCapture

#include "Basic.hpp"

#include "AudioMixer_classes.hpp"


namespace SDK
{

// Class AudioCapture.AudioCaptureComponent
// 0x00B0 (0x0670 - 0x05C0)
class UAudioCaptureComponent final : public USynthComponent
{
public:
	int32                                         JitterLatencyFrames;                               // 0x05C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5C4[0xAC];                                     // 0x05C4(0x00AC)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioCaptureComponent">();
	}
	static class UAudioCaptureComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioCaptureComponent>();
	}
};

}

