#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Cupboard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Cupboard.BP_Cupboard_C
// 0x0030 (0x04B0 - 0x0480)
class ABP_Cupboard_C final : public ACupboard
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0480(0x0008)(Transient, DuplicateTransient)
	class UNeighborLocationComponent*             NeighborLocation;                                  // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMovingComponent*                       Left;                                              // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMovingComponent*                       Right;                                             // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        wood_cupboard_closed_Cue;                          // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        wood_cupboard_open_Cue;                            // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Cupboard(int32 EntryPoint);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);
	void UserConstructionScript();
	void OnEventAction(class AActor* ActionMaker, class UPrimitiveComponent* SpecialComponent);
	void OnChangeDoorState(EDoorState NewState);
	void BndEvt__Right_K2Node_ComponentBoundEvent_0_ChangeState__DelegateSignature(EMovingState NewState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Cupboard_C">();
	}
	static class ABP_Cupboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cupboard_C>();
	}
};

}

