#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Flashlight

#include "Basic.hpp"

#include "HelloNeighbor_structs.hpp"


namespace SDK::Params
{

// Function BP_Flashlight.BP_Flashlight_C.ExecuteUbergraph_BP_Flashlight
// 0x0020 (0x0020 - 0x0000)
struct BP_Flashlight_C_ExecuteUbergraph_BP_Flashlight final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class AActor*                                 K2Node_Event_ActionMaker;                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_SpecialComponent;                     // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETumblerState                                 CallFunc_GetTumblerState_ReturnValue;              // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ETumblerState                                 K2Node_Event_NewState;                             // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum1_CmpSuccess;                     // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_Flashlight.BP_Flashlight_C.OnIsActionComponent
// 0x0010 (0x0010 - 0x0000)
struct BP_Flashlight_C_OnIsActionComponent final
{
public:
	class UPrimitiveComponent*                    Component;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_Flashlight.BP_Flashlight_C.UpdateData
// 0x0002 (0x0002 - 0x0000)
struct BP_Flashlight_C_UpdateData final
{
public:
	ETumblerState                                 CallFunc_GetTumblerState_ReturnValue;              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_Flashlight.BP_Flashlight_C.OnEventAction
// 0x0010 (0x0010 - 0x0000)
struct BP_Flashlight_C_OnEventAction final
{
public:
	class AActor*                                 ActionMaker;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    SpecialComponent;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_Flashlight.BP_Flashlight_C.OnChangeTumblerState
// 0x0001 (0x0001 - 0x0000)
struct BP_Flashlight_C_OnChangeTumblerState final
{
public:
	ETumblerState                                 NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

