#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_FireTrail

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FireTrail.BP_FireTrail_C
// 0x0018 (0x0488 - 0x0470)
class ABP_FireTrail_C final : public AFireTrail
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0470(0x0008)(Transient, DuplicateTransient)
	class UBillboardComponent*                    Billboard;                                         // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_FireTrail(int32 EntryPoint);
	void UserConstructionScript();
	void OnChangeTemperature(float Temperature);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FireTrail_C">();
	}
	static class ABP_FireTrail_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FireTrail_C>();
	}
};

}

