#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Flashlight

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Flashlight.BP_Flashlight_C
// 0x0008 (0x04A8 - 0x04A0)
class ABP_Flashlight_C final : public AFlashlight
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Flashlight(int32 EntryPoint);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);
	void UpdateData();
	void UserConstructionScript();
	void OnEventAction(class AActor* ActionMaker, class UPrimitiveComponent* SpecialComponent);
	void OnChangeTumblerState(ETumblerState NewState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Flashlight_C">();
	}
	static class ABP_Flashlight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Flashlight_C>();
	}
};

}

