#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_GameInstance

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_GameInstance.BP_GameInstance_C.ExecuteUbergraph_BP_GameInstance
// 0x0030 (0x0030 - 0x0000)
struct BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	TDelegate<void(bool Save)>                    K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	class UBPW_LoadingIcon_C*                     CallFunc_Create_ReturnValue;                       // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveSystem*                            CallFunc_GetSaveSystem_ReturnValue;                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Save;                           // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_GameInstance.BP_GameInstance_C.OnSaveGame_Event_0
// 0x0001 (0x0001 - 0x0000)
struct BP_GameInstance_C_OnSaveGame_Event_0 final
{
public:
	bool                                          Save;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

