#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_HolderCamera

#include "Basic.hpp"

#include "BP_HolderCamera_classes.hpp"


namespace SDK
{

// Function BP_HolderCamera.BP_HolderCamera_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_HolderCamera_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HolderCamera_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

