#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_LadderGate

#include "Basic.hpp"

#include "HelloNeighbor_structs.hpp"


namespace SDK::Params
{

// Function BP_LadderGate.BP_LadderGate_C.ExecuteUbergraph_BP_LadderGate
// 0x0018 (0x0018 - 0x0000)
struct BP_LadderGate_C_ExecuteUbergraph_BP_LadderGate final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMovingState                                  CallFunc_GetMovingState_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-8 ])
	struct FJSON                                  K2Node_Event_JsonObject;                           // 0x0008(0x0008)(ConstParm, NoDestructor)
	bool                                          CallFunc_IsPlaying_ReturnValue;                    // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetValueAsBool_BoolValue;                 // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetValueAsBool_ReturnValue;               // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EMovingState                                  K2Node_ComponentBoundEvent_NewState;               // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_LadderGate.BP_LadderGate_C.OnIsActionComponent
// 0x0010 (0x0010 - 0x0000)
struct BP_LadderGate_C_OnIsActionComponent final
{
public:
	class UPrimitiveComponent*                    Component;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_LadderGate.BP_LadderGate_C.OnLoad
// 0x0008 (0x0008 - 0x0000)
struct BP_LadderGate_C_OnLoad final
{
public:
	struct FJSON                                  JsonObject;                                        // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};

// Function BP_LadderGate.BP_LadderGate_C.BndEvt__RightDoor_K2Node_ComponentBoundEvent_0_ChangeState__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct BP_LadderGate_C_BndEvt__RightDoor_K2Node_ComponentBoundEvent_0_ChangeState__DelegateSignature final
{
public:
	EMovingState                                  NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_LadderGate.BP_LadderGate_C.OnSave
// 0x0010 (0x0010 - 0x0000)
struct BP_LadderGate_C_OnSave final
{
public:
	struct FJSON                                  JsonObject;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	EMovingState                                  CallFunc_GetMovingState_ReturnValue;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

