#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_MillMagnet

#include "Basic.hpp"

#include "HelloNeighbor_structs.hpp"


namespace SDK::Params
{

// Function BP_MillMagnet.BP_MillMagnet_C.ExecuteUbergraph_BP_MillMagnet
// 0x0008 (0x0008 - 0x0000)
struct BP_MillMagnet_C_ExecuteUbergraph_BP_MillMagnet final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlaying_ReturnValue;                    // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ETumblerState                                 K2Node_Event_NewState;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlaying_ReturnValue1;                   // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_MillMagnet.BP_MillMagnet_C.OnChangeState
// 0x0001 (0x0001 - 0x0000)
struct BP_MillMagnet_C_OnChangeState final
{
public:
	ETumblerState                                 NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

