#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_MillMagnet

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MillMagnet.BP_MillMagnet_C
// 0x0030 (0x04F0 - 0x04C0)
class ABP_MillMagnet_C final : public AMillMagnet
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(Transient, DuplicateTransient)
	class UAudioComponent*                        mechanism_buzz_Cue;                                // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class AFlatActor*>                     FlatActors;                                        // 0x04D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance)
	float                                         MaxSpeedRotation_0;                                // 0x04E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Acceleration_0;                                    // 0x04E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurSpeedRotation;                                  // 0x04E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MillMagnet(int32 EntryPoint);
	void UserConstructionScript();
	void OnChangeState(ETumblerState NewState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MillMagnet_C">();
	}
	static class ABP_MillMagnet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MillMagnet_C>();
	}
};

}

