#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_MillButtonClear

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MillButtonClear.BP_MillButtonClear_C
// 0x0020 (0x0460 - 0x0440)
class ABP_MillButtonClear_C final : public AIntaractive
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0440(0x0008)(Transient, DuplicateTransient)
	class UAudioComponent*                        on_off_switch_Cue;                                 // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMovingComponent*                       Arm;                                               // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_NewMillMechanism_C*                 MillMechanism;                                     // 0x0458(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MillButtonClear(int32 EntryPoint);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);
	void UserConstructionScript();
	void OnEventAction(class AActor* ActionMaker, class UPrimitiveComponent* SpecialComponent);
	void BndEvt__Arm_K2Node_ComponentBoundEvent_0_ChangeState__DelegateSignature(EMovingState NewState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MillButtonClear_C">();
	}
	static class ABP_MillButtonClear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MillButtonClear_C>();
	}
};

}

