#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_NotifyKnockDoor

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NotifyKnockDoor.BP_NotifyKnockDoor_C
// 0x0008 (0x0040 - 0x0038)
class UBP_NotifyKnockDoor_C final : public UNativeAnimNotify
{
public:
	class ABP_Kithen_sink_C*                      NewVar_0;                                          // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NotifyKnockDoor_C">();
	}
	static class UBP_NotifyKnockDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NotifyKnockDoor_C>();
	}
};

}

