#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_NotifyCloseDoor

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NotifyCloseDoor.BP_NotifyCloseDoor_C
// 0x0000 (0x0038 - 0x0038)
class UBP_NotifyCloseDoor_C final : public UNativeAnimNotify
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NotifyCloseDoor_C">();
	}
	static class UBP_NotifyCloseDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NotifyCloseDoor_C>();
	}
};

}

