#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_NotifyOpenDoor

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NotifyOpenDoor.BP_NotifyOpenDoor_C
// 0x0000 (0x0038 - 0x0038)
class UBP_NotifyOpenDoor_C final : public UNativeAnimNotify
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NotifyOpenDoor_C">();
	}
	static class UBP_NotifyOpenDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NotifyOpenDoor_C>();
	}
};

}

