#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_NotifyPushActor

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NotifyPushActor.BP_NotifyPushActor_C
// 0x0000 (0x0038 - 0x0038)
class UBP_NotifyPushActor_C final : public UNativeAnimNotify
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NotifyPushActor_C">();
	}
	static class UBP_NotifyPushActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NotifyPushActor_C>();
	}
};

}

