#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Platform

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Platform.BP_Platform_C
// 0x0030 (0x0478 - 0x0448)
class ABP_Platform_C final : public AElectric
{
public:
	uint8                                         Pad_448[0x8];                                      // 0x0448(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(Transient, DuplicateTransient)
	class UAudioComponent*                        gate_opening_Cue;                                  // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        open_gate_Cue;                                     // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMovingComponent*                       Platform;                                          // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Platform(int32 EntryPoint);
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void OnChangeConnection();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Platform_C">();
	}
	static class ABP_Platform_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Platform_C>();
	}
};

}

