#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Proxy

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Proxy.BP_Proxy_C
// 0x0010 (0x0338 - 0x0328)
class ABP_Proxy_C final : public AActor
{
public:
	class UNavLinkerComponent*                    NavLinker;                                         // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    Billboard;                                         // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Proxy_C">();
	}
	static class ABP_Proxy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Proxy_C>();
	}
};

}

