#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Proxy

#include "Basic.hpp"

#include "BP_Proxy_classes.hpp"


namespace SDK
{

// Function BP_Proxy.BP_Proxy_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Proxy_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Proxy_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

