#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Switcher

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Switcher.BP_Switcher_C
// 0x0010 (0x0490 - 0x0480)
class ABP_Switcher_C final : public ATumbler
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0480(0x0008)(Transient, DuplicateTransient)
	class UMovingComponent*                       SWITCH;                                            // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Switcher(int32 EntryPoint);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);
	void UserConstructionScript();
	void OnEventAction(class AActor* ActionMaker, class UPrimitiveComponent* SpecialComponent);
	void OnChangeTumblerState(ETumblerState NewState);
	void ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void BndEvt__Switch_K2Node_ComponentBoundEvent_1_ChangeState__DelegateSignature(EMovingState NewState);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Switcher_C">();
	}
	static class ABP_Switcher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Switcher_C>();
	}
};

}

