#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Sosed

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Sosed.BP_Sosed_C
// 0x0050 (0x0C90 - 0x0C40)
class ABP_Sosed_C final : public ASosed
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0C40(0x0008)(Transient, DuplicateTransient)
	class UArrowComponent*                        ArrowJump;                                         // 0x0C48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        ArrowLeftFoot;                                     // 0x0C50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        ArrowRightFoot;                                    // 0x0C58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        attack_sound;                                      // 0x0C60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         FlashlightRadius;                                  // 0x0C68(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C6C[0x4];                                      // 0x0C6C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FTimerHandle                           SoundHandle;                                       // 0x0C70(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          NeedPlaySoundAttack;                               // 0x0C78(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C79[0x7];                                      // 0x0C79(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class USoundBase*                             SoundStruck;                                       // 0x0C80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Sosed(int32 EntryPoint);
	void ConnectFlashlight();
	void Run_Footstep(class USceneComponent* FootArrow);
	void Jump_Footstep(class USceneComponent* FootArrow);
	void Walk_Footstep(class USceneComponent* FootArrow);
	void ChangeMaterial(class UPhysicalMaterial* Mat, const struct FTransform& SpawnTransform, bool Run, bool Walk);
	void CreateHolderCamera(class AActor** HolderCamera);
	void CreateCamera(class AVideoCamera** Camera);
	void UserConstructionScript();
	void MixerButtonEvt_Toggle_Electricity_Pressed(const struct FMixerButtonReference& Button, int32 ParticipantId, const struct FMixerTransactionId& TransactionId, int32 SparkCost);
	void MixerButtonEvt_Kick_the_Neighbor_Pressed(const struct FMixerButtonReference& Button, int32 ParticipantId, const struct FMixerTransactionId& TransactionId, int32 SparkCost);
	void OnChangeState(ENeighborState State);
	void Foot_Left_Walk();
	void Foot_Right_Walk();
	void JumpFootSteps();
	void Run_Left_Foot();
	void Run_Right_Foot();
	void Walk_Water();
	void Walk_Earth();
	void Walk_Tile();
	void Walk_Grass();
	void Walk_Wood();
	void Walk_Road();
	void Walk_Glue();
	void Walk_Carpet();
	void Walk_Metal();
	void Walk_Flour();
	void Run_Water();
	void Run_Earth();
	void Run_Grass();
	void Run_Wood();
	void Run_Tile();
	void Run_Road();
	void Run_Glue();
	void Run_Carpet();
	void Run_Metal();
	void Run_Flour();
	void Jump_Water();
	void Jump_Earth();
	void Jump_Tile();
	void Jump_Grass();
	void Jump_Wood();
	void Jump_Road();
	void Jump_Glue();
	void Jump_Carpet();
	void Jump_Metal();
	void Jump_Flour();
	void Walk_Furniture();
	void Run_Furniture();
	void Jump_Furniture();
	void OnThrowGlue(class AHuman* Human);
	void ReceiveBeginPlay();
	void OnRefreshGameData();
	void OnThrowTomato(class AHuman* Human);
	void Walk_Ice();
	void Run_Ice();
	void Jump_Ice();
	void Walk_Plastic();
	void Run_Plastic();
	void Jump_Plastic();
	void Walk_Rail();
	void Run_Rail();
	void Jump_Rail();
	void TimerSound();
	void OnStruck();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Sosed_C">();
	}
	static class ABP_Sosed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Sosed_C>();
	}
};

}

