#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Trap

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Trap.BP_Trap_C.ExecuteUbergraph_BP_Trap
// 0x0004 (0x0004 - 0x0000)
struct BP_Trap_C_ExecuteUbergraph_BP_Trap final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_Trap.BP_Trap_C.OnIsActionComponent
// 0x0010 (0x0010 - 0x0000)
struct BP_Trap_C_OnIsActionComponent final
{
public:
	class UPrimitiveComponent*                    Component;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

