#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_VideoCamera

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VideoCamera.BP_VideoCamera_C
// 0x0020 (0x04D0 - 0x04B0)
class ABP_VideoCamera_C final : public AVideoCamera
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B0(0x0008)(Transient, DuplicateTransient)
	class UAudioComponent*                        electrical_spark_1_Cue;                            // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        camera_metal_crunch_Cue;                           // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        camera_electric_spark_Cue;                         // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_VideoCamera(int32 EntryPoint);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);
	void CreateHolderCamera(class AActor** HolderCamera);
	void UserConstructionScript();
	void OnChangeCamera();
	void OnChangeConnection();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VideoCamera_C">();
	}
	static class ABP_VideoCamera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VideoCamera_C>();
	}
};

}

