#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_VacuumCleaner

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VacuumCleaner.BP_VacuumCleaner_C
// 0x0008 (0x0338 - 0x0330)
class ABP_VacuumCleaner_C final : public AVacuumCleaner
{
public:
	class UAudioComponent*                        Audio;                                             // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VacuumCleaner_C">();
	}
	static class ABP_VacuumCleaner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VacuumCleaner_C>();
	}
};

}

