#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_VacuumCleaner

#include "Basic.hpp"

#include "BP_VacuumCleaner_classes.hpp"


namespace SDK
{

// Function BP_VacuumCleaner.BP_VacuumCleaner_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_VacuumCleaner_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VacuumCleaner_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

