#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Window_4

#include "Basic.hpp"

#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Window_4.BP_Window_4_C
// 0x0000 (0x0510 - 0x0510)
class ABP_Window_4_C final : public AWindow
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Window_4_C">();
	}
	static class ABP_Window_4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Window_4_C>();
	}
};

}

