#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_NavigationMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_NavigationMenu.BPW_NavigationMenu_C
// 0x0918 (0x0B20 - 0x0208)
class UBPW_NavigationMenu_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0208(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 Img_Back1;                                         // 0x0210(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Back2;                                         // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Back3;                                         // 0x0220(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Default1;                                      // 0x0228(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Del1;                                          // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Select1;                                       // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Select2;                                       // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Select3;                                       // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        SWITCH;                                            // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Back1;                                          // 0x0258(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Back2;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Back3;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Default1;                                       // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Del1;                                           // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Select1;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Select2;                                        // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Select3;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSlateBrush                            BrushWindowsBack;                                  // 0x0298(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushWindowsSelect;                                // 0x0320(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushXBoxBack;                                     // 0x03A8(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushXBoxSelect;                                   // 0x0430(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushPs4Back;                                      // 0x04B8(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushPs4Select;                                    // 0x0540(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushSwitchBack;                                   // 0x05C8(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushSwitchSelect;                                 // 0x0650(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	ELanguage                                     CurLanguage;                                       // 0x06D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPlatform                                     Platform;                                          // 0x06D9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6DA[0x6];                                      // 0x06DA(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSlateBrush                            BrushWindowsDel;                                   // 0x06E0(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushXBoxDel;                                      // 0x0768(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushPs4Del;                                       // 0x07F0(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushSwitchDel;                                    // 0x0878(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushWindowsDefault;                               // 0x0900(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushXBoxDefault;                                  // 0x0988(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushPs4Default;                                   // 0x0A10(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            BrushSwitchDefault;                                // 0x0A98(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BPW_NavigationMenu(int32 EntryPoint);
	void SetModelDefaultBackSelect();
	void SetModelDelBackSelect();
	void SetModelBackSelect();
	void OnKey(const struct FKey& Key);
	void ChangeTexts(ELanguage Language);
	void GetText(class FName Name_0, class FText* LocText);
	void Construct();
	void OnChangeLanguage(ELanguage NewLanguage);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_NavigationMenu_C">();
	}
	static class UBPW_NavigationMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_NavigationMenu_C>();
	}
};

}

