#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_NavigationMenu

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "SlateCore_structs.hpp"
#include "LocStruct_structs.hpp"


namespace SDK::Params
{

// Function BPW_NavigationMenu.BPW_NavigationMenu_C.ExecuteUbergraph_BPW_NavigationMenu
// 0x00B8 (0x00B8 - 0x0000)
struct BPW_NavigationMenu_C_ExecuteUbergraph_BPW_NavigationMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPlatform                                     CallFunc_GetPlatform_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-8 ])
	TDelegate<void(ELanguage NewLanguage)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	struct FKey                                   Temp_struct_Variable;                              // 0x0018(0x0018)(HasGetValueTypeHash)
	struct FKey                                   Temp_struct_Variable1;                             // 0x0030(0x0018)(HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ELanguage                                     K2Node_CustomEvent_NewLanguage;                    // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UHelloNeighborGameInstance*             K2Node_DynamicCast_AsHello_Neighbor_Game_Instance; // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	struct FGameParams                            CallFunc_GetGameParams_ReturnValue;                // 0x0064(0x0034)(ConstParm, NoDestructor)
	bool                                          CallFunc_IsLastPressGamepadKey_ReturnValue;        // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FKey                                   K2Node_Select_Default;                             // 0x00A0(0x0018)(HasGetValueTypeHash)
};

// Function BPW_NavigationMenu.BPW_NavigationMenu_C.OnKey
// 0x1140 (0x1140 - 0x0000)
struct BPW_NavigationMenu_C_OnKey final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	EPlatform                                     Temp_byte_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue;             // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSlateBrush                            Temp_struct_Variable;                              // 0x0020(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable1;                             // 0x00A8(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable2;                             // 0x0130(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable3;                             // 0x01B8(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable4;                             // 0x0240(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable5;                             // 0x02C8(0x0088)()
	bool                                          Temp_bool_Variable;                                // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     Temp_byte_Variable1;                               // 0x0351(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_352[0x6];                                      // 0x0352(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSlateBrush                            Temp_struct_Variable6;                             // 0x0358(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable7;                             // 0x03E0(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable8;                             // 0x0468(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable9;                             // 0x04F0(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable10;                            // 0x0578(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable11;                            // 0x0600(0x0088)()
	bool                                          Temp_bool_Variable1;                               // 0x0688(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable2;                               // 0x0689(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     Temp_byte_Variable2;                               // 0x068A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_68B[0x5];                                      // 0x068B(0x0005)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSlateBrush                            Temp_struct_Variable12;                            // 0x0690(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable13;                            // 0x0718(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable14;                            // 0x07A0(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable15;                            // 0x0828(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable16;                            // 0x08B0(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable17;                            // 0x0938(0x0088)()
	EPlatform                                     Temp_byte_Variable3;                               // 0x09C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C1[0x7];                                      // 0x09C1(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSlateBrush                            Temp_struct_Variable18;                            // 0x09C8(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable19;                            // 0x0A50(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable20;                            // 0x0AD8(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable21;                            // 0x0B60(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable22;                            // 0x0BE8(0x0088)()
	struct FSlateBrush                            Temp_struct_Variable23;                            // 0x0C70(0x0088)()
	bool                                          Temp_bool_Variable3;                               // 0x0CF8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CF9[0x7];                                      // 0x0CF9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSlateBrush                            K2Node_Select_Default;                             // 0x0D00(0x0088)()
	struct FSlateBrush                            K2Node_Select1_Default;                            // 0x0D88(0x0088)()
	struct FSlateBrush                            K2Node_Select2_Default;                            // 0x0E10(0x0088)()
	struct FSlateBrush                            K2Node_Select3_Default;                            // 0x0E98(0x0088)()
	struct FSlateBrush                            K2Node_Select4_Default;                            // 0x0F20(0x0088)()
	struct FSlateBrush                            K2Node_Select5_Default;                            // 0x0FA8(0x0088)()
	struct FSlateBrush                            K2Node_Select6_Default;                            // 0x1030(0x0088)()
	struct FSlateBrush                            K2Node_Select7_Default;                            // 0x10B8(0x0088)()
};

// Function BPW_NavigationMenu.BPW_NavigationMenu_C.ChangeTexts
// 0x0068 (0x0068 - 0x0000)
struct BPW_NavigationMenu_C_ChangeTexts final
{
public:
	ELanguage                                     Language;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   CallFunc_GetText_LocText;                          // 0x0008(0x0018)()
	class FText                                   CallFunc_GetText_LocText1;                         // 0x0020(0x0018)()
	class FText                                   CallFunc_GetText_LocText2;                         // 0x0038(0x0018)()
	class FText                                   CallFunc_GetText_LocText3;                         // 0x0050(0x0018)()
};

// Function BPW_NavigationMenu.BPW_NavigationMenu_C.GetText
// 0x02A0 (0x02A0 - 0x0000)
struct BPW_NavigationMenu_C_GetText final
{
public:
	class FName                                   Name_0;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   LocText;                                           // 0x0008(0x0018)(Parm, OutParm)
	ELanguage                                     Temp_byte_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FLocStruct                             CallFunc_GetDataTableRowFromName_OutRow;           // 0x0028(0x0258)(HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   K2Node_Select_Default;                             // 0x0288(0x0018)()
};

// Function BPW_NavigationMenu.BPW_NavigationMenu_C.OnChangeLanguage
// 0x0001 (0x0001 - 0x0000)
struct BPW_NavigationMenu_C_OnChangeLanguage final
{
public:
	ELanguage                                     NewLanguage;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

