#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_RequestQuit

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"
#include "ECloseWindow_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_RequestQuit.BPW_RequestQuit_C
// 0x0550 (0x0758 - 0x0208)
class UBPW_RequestQuit_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0208(0x0008)(Transient, DuplicateTransient)
	class UButton*                                BT_No;                                             // 0x0210(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                BT_Yes;                                            // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_No;                                             // 0x0220(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TB_Yes;                                            // 0x0228(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x0230(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	ELanguage                                     CurLanguage;                                       // 0x0238(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_239[0x7];                                      // 0x0239(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class AHelloNeighborRebornGameMode*           GameMode;                                          // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UButton*                                ActiveButton;                                      // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FButtonStyle                           ActiveStyle;                                       // 0x0250(0x0278)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FButtonStyle                           DeActiveStyle;                                     // 0x04C8(0x0278)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UBPW_MenuPause_C*                       Parent;                                            // 0x0740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	UMulticastDelegateProperty_                   Destroy;                                           // 0x0748(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_BPW_RequestQuit(int32 EntryPoint);
	class FText Descr_Text();
	void Init(class UBPW_MenuPause_C* NewParam);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	void GetText(class FName Text, class FText* LocText);
	class FText descr_no();
	class FText descr_yes();
	void OnFocusLost(const struct FFocusEvent& InFocusEvent);
	void PressLeft();
	void PressRight();
	void PressEnter();
	void PressBack();
	void Construct();
	void OnControllerConnect();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_RequestQuit_C">();
	}
	static class UBPW_RequestQuit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_RequestQuit_C>();
	}
};

// LinkerPlaceholderClass BPW_RequestQuit.PLACEHOLDER-CLASS__BPW_MenuPause_C_0
// 0x0000 (0x0000 - 0x0000)
class UPLACEHOLDER_CLASS__BPW_MenuPause_C_0 final
{
public:
};

}

