#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_MixerKickNeighbor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPW_MixerKickNeighbor.BPW_MixerKickNeighbor_C.ExecuteUbergraph_BPW_MixerKickNeighbor
// 0x0010 (0x0010 - 0x0000)
struct BPW_MixerKickNeighbor_C_ExecuteUbergraph_BPW_MixerKickNeighbor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	const class UWidgetAnimation*                 K2Node_Event_Animation;                            // 0x0008(0x0008)(ConstParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BPW_MixerKickNeighbor.BPW_MixerKickNeighbor_C.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct BPW_MixerKickNeighbor_C_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

