#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_GameLoading

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPW_GameLoading.BPW_GameLoading_C.ExecuteUbergraph_BPW_GameLoading
// 0x0004 (0x0004 - 0x0000)
struct BPW_GameLoading_C_ExecuteUbergraph_BPW_GameLoading final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

