#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_Loading

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_Loading.BPW_Loading_C
// 0x0000 (0x0208 - 0x0208)
class UBPW_Loading_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_Loading_C">();
	}
	static class UBPW_Loading_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_Loading_C>();
	}
};

}

