#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_KeyHole

#include "Basic.hpp"

#include "BPW_KeyHole_classes.hpp"
#include "BPW_KeyHole_parameters.hpp"


namespace SDK
{

// Function BPW_KeyHole.BPW_KeyHole_C.SetAlpha
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_KeyHole_C::SetAlpha(float Alpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_KeyHole_C", "SetAlpha");

	Params::BPW_KeyHole_C_SetAlpha Parms{};

	Parms.Alpha = Alpha;

	UObject::ProcessEvent(Func, &Parms);
}

}

