#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_GameConsole

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "InputCore_structs.hpp"
#include "HelloNeighbor_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BPW_GameConsole.BPW_GameConsole_C.ExecuteUbergraph_BPW_GameConsole
// 0x0400 (0x0400 - 0x0000)
struct BPW_GameConsole_C_ExecuteUbergraph_BPW_GameConsole final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	class FText                                   Temp_text_Variable1;                               // 0x0020(0x0018)()
	bool                                          Temp_bool_Variable1;                               // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   Temp_text_Variable2;                               // 0x0040(0x0018)()
	class FText                                   Temp_text_Variable3;                               // 0x0058(0x0018)()
	bool                                          Temp_bool_Variable2;                               // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   Temp_text_Variable4;                               // 0x0078(0x0018)()
	class FText                                   Temp_text_Variable5;                               // 0x0090(0x0018)()
	bool                                          Temp_bool_Variable3;                               // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   Temp_text_Variable6;                               // 0x00B0(0x0018)()
	class FText                                   Temp_text_Variable7;                               // 0x00C8(0x0018)()
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue1;         // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue;             // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x00F8(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_112[0x6];                                      // 0x0112(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0118(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable4;                               // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_132[0x2];                                      // 0x0132(0x0002)(Fixing Size After Last Property [ Dumper-8 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0134(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue2;         // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0178(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue1;             // 0x0190(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue2;             // 0x01A8(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue3;             // 0x01C0(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue4;             // 0x01D8(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue5;             // 0x01F0(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue6;             // 0x0208(0x0018)()
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue7;             // 0x0228(0x0018)()
	class UHelloNeighborGameInstance*             K2Node_DynamicCast_AsHello_Neighbor_Game_Instance; // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_249[0x3];                                      // 0x0249(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	struct FGameParams                            CallFunc_GetGameParams_ReturnValue;                // 0x024C(0x0034)(ConstParm, NoDestructor)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue8;             // 0x0280(0x0018)()
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TDelegate<void(class FText Command)>          K2Node_CreateDelegate_OutputDelegate;              // 0x02A0(0x0010)(ZeroConstructor, NoDestructor)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue9;             // 0x02B0(0x0018)()
	class UBPW_Loading_C*                         CallFunc_Create_ReturnValue;                       // 0x02C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHelloNeighborRebornGameMode*           K2Node_DynamicCast_AsHello_Neighbor_Reborn_Game_Mode; // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess1;                      // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E1[0x7];                                      // 0x02E1(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class AHuman*                                 CallFunc_FindHuman_ReturnValue;                    // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHuman*                                 CallFunc_FindHuman_ReturnValue1;                   // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_Command;                        // 0x02F8(0x0018)()
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue;          // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue1;         // 0x0311(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue2;         // 0x0312(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue3;         // 0x0313(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   Temp_text_Variable8;                               // 0x0318(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue10;            // 0x0330(0x0018)()
	class AHuman*                                 CallFunc_FindHuman_ReturnValue2;                   // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue11;            // 0x0350(0x0018)()
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue4;         // 0x0368(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue1;         // 0x0369(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_36A[0x6];                                      // 0x036A(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   K2Node_Select_Default;                             // 0x0370(0x0018)()
	class FText                                   K2Node_Select1_Default;                            // 0x0388(0x0018)()
	class FText                                   K2Node_Select2_Default;                            // 0x03A0(0x0018)()
	class FText                                   K2Node_Select3_Default;                            // 0x03B8(0x0018)()
	class FText                                   Temp_text_Variable9;                               // 0x03D0(0x0018)()
	class FText                                   K2Node_Select4_Default;                            // 0x03E8(0x0018)()
};

// Function BPW_GameConsole.BPW_GameConsole_C.OnKeyUp
// 0x0240 (0x0240 - 0x0000)
struct BPW_GameConsole_C_OnKeyUp final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FKey                                   Tilde1;                                            // 0x0128(0x0018)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FKey                                   Tilde2;                                            // 0x0140(0x0018)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0158(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue1;           // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_172[0x6];                                      // 0x0172(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	class AHuman*                                 CallFunc_FindHuman_ReturnValue;                    // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0188(0x00B8)()
};

// Function BPW_GameConsole.BPW_GameConsole_C.AddString
// 0x0038 (0x0038 - 0x0000)
struct BPW_GameConsole_C_AddString final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FLinearColor                           Color;                                             // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBPW_ConsoleString_C*                   CallFunc_Create_ReturnValue;                       // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BPW_GameConsole.BPW_GameConsole_C.BndEvt__EditableBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BPW_GameConsole_C_BndEvt__EditableBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BPW_GameConsole.BPW_GameConsole_C.Tick
// 0x003C (0x003C - 0x0000)
struct BPW_GameConsole_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BPW_GameConsole.BPW_GameConsole_C.OnFailedCommand
// 0x0018 (0x0018 - 0x0000)
struct BPW_GameConsole_C_OnFailedCommand final
{
public:
	class FText                                   Command;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

}

