#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_EnterKey

#include "Basic.hpp"

#include "HelloNeighbor_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "InputCore_structs.hpp"
#include "LocStruct_structs.hpp"


namespace SDK::Params
{

// Function BPW_EnterKey.BPW_EnterKey_C.ExecuteUbergraph_BPW_EnterKey
// 0x0168 (0x0168 - 0x0000)
struct BPW_EnterKey_C_ExecuteUbergraph_BPW_EnterKey final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FKey                                   K2Node_CustomEvent_Key;                            // 0x0010(0x0018)(HasGetValueTypeHash)
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue;           // 0x0028(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x0058(0x0008)(NoDestructor)
	class UHelloNeighborGameInstance*             K2Node_DynamicCast_AsHello_Neighbor_Game_Instance; // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue1;             // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameParams                            CallFunc_GetGameParams_ReturnValue;                // 0x0078(0x0034)(ConstParm, NoDestructor)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x00AC(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerEvent                          K2Node_Event_MouseEvent;                           // 0x00F0(0x0070)(ConstParm)
	bool                                          CallFunc_Set_Contains_ReturnValue;                 // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue; // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue1; // 0x0162(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue2; // 0x0163(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BPW_EnterKey.BPW_EnterKey_C.Init
// 0x0230 (0x0230 - 0x0000)
struct BPW_EnterKey_C_Init final
{
public:
	EInputAction                                  Action_0;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputAction                                  Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   CallFunc_GetText_LocText;                          // 0x0008(0x0018)()
	class FText                                   CallFunc_GetText_LocText1;                         // 0x0020(0x0018)()
	class FText                                   CallFunc_GetText_LocText2;                         // 0x0038(0x0018)()
	class FText                                   CallFunc_GetText_LocText3;                         // 0x0050(0x0018)()
	class FText                                   CallFunc_GetText_LocText4;                         // 0x0068(0x0018)()
	class FText                                   CallFunc_GetText_LocText5;                         // 0x0080(0x0018)()
	class FText                                   CallFunc_GetText_LocText6;                         // 0x0098(0x0018)()
	class FText                                   CallFunc_GetText_LocText7;                         // 0x00B0(0x0018)()
	class FText                                   CallFunc_GetText_LocText8;                         // 0x00C8(0x0018)()
	class FText                                   CallFunc_GetText_LocText9;                         // 0x00E0(0x0018)()
	class FText                                   CallFunc_GetText_LocText10;                        // 0x00F8(0x0018)()
	class FText                                   CallFunc_GetText_LocText11;                        // 0x0110(0x0018)()
	class FText                                   CallFunc_GetText_LocText12;                        // 0x0128(0x0018)()
	class FText                                   CallFunc_GetText_LocText13;                        // 0x0140(0x0018)()
	class FText                                   CallFunc_GetText_LocText14;                        // 0x0158(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0170(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0188(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData1;             // 0x01C8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0208(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0218(0x0018)()
};

// Function BPW_EnterKey.BPW_EnterKey_C.OnKeyDown
// 0x0218 (0x0218 - 0x0000)
struct BPW_EnterKey_C_OnKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0128(0x00B8)()
	struct FInputEvent                            CallFunc_GetInputEventFromKeyEvent_ReturnValue;    // 0x01E0(0x0018)()
	bool                                          CallFunc_InputEvent_IsRepeat_ReturnValue;          // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F9[0x7];                                      // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0200(0x0018)(HasGetValueTypeHash)
};

// Function BPW_EnterKey.BPW_EnterKey_C.GetText
// 0x02A0 (0x02A0 - 0x0000)
struct BPW_EnterKey_C_GetText final
{
public:
	class FName                                   Text;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   LocText;                                           // 0x0008(0x0018)(Parm, OutParm)
	ELanguage                                     Temp_byte_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FLocStruct                             CallFunc_GetDataTableRowFromName_OutRow;           // 0x0028(0x0258)(HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   K2Node_Select_Default;                             // 0x0288(0x0018)()
};

// Function BPW_EnterKey.BPW_EnterKey_C.PressEnter
// 0x0018 (0x0018 - 0x0000)
struct BPW_EnterKey_C_PressEnter final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};

// Function BPW_EnterKey.BPW_EnterKey_C.OnFocusLost
// 0x0008 (0x0008 - 0x0000)
struct BPW_EnterKey_C_OnFocusLost final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};

// Function BPW_EnterKey.BPW_EnterKey_C.Tick
// 0x003C (0x003C - 0x0000)
struct BPW_EnterKey_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BPW_EnterKey.BPW_EnterKey_C.OnMouseLeave
// 0x0070 (0x0070 - 0x0000)
struct BPW_EnterKey_C_OnMouseLeave final
{
public:
	struct FPointerEvent                          MouseEvent;                                        // 0x0000(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

}

