#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPW_KeyHole

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_KeyHole.BPW_KeyHole_C
// 0x0008 (0x0210 - 0x0208)
class UBPW_KeyHole_C final : public UUserWidget
{
public:
	class UImage*                                 Image_37;                                          // 0x0208(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetAlpha(float Alpha);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_KeyHole_C">();
	}
	static class UBPW_KeyHole_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_KeyHole_C>();
	}
};

}

