#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonSelector

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK
{

// UserDefinedStruct ButtonSelector.ButtonSelector
// 0x0508 (0x0508 - 0x0000)
struct FButtonSelector final
{
public:
	TArray<class UButton*>                        Buttons_3_8D0AA06A47DD998A1F64ABBC8D0F4890;        // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	int32                                         Selector_7_36858C1A419C383AA9DB66BF7A5C75C4;       // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FButtonStyle                           StyleSelect_10_79C70AC940527CC5182B809FBE6FFF92;   // 0x0018(0x0278)(Edit, BlueprintVisible)
	struct FButtonStyle                           StyleUnSelect_12_0C15EB74477BA9795FAED283E82345C6; // 0x0290(0x0278)(Edit, BlueprintVisible)
};

}

