#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ECloseWindow

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ECloseWindow.ECloseWindow
// NumValues: 0x0004
enum class ECloseWindow : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	ECloseWindow_MAX                         = 3,
};

}

