#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EGateState

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EGateState.EGateState
// NumValues: 0x0005
enum class EGateState : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	EGateState_MAX                           = 4,
};

}

