#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EHNMenu

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EHNMenu.EHNMenu
// NumValues: 0x0013
enum class EHNMenu : uint8
{
	NewEnumerator13                          = 0,
	NewEnumerator14                          = 1,
	NewEnumerator15                          = 2,
	NewEnumerator17                          = 3,
	NewEnumerator2                           = 4,
	NewEnumerator16                          = 5,
	NewEnumerator0                           = 6,
	NewEnumerator1                           = 7,
	NewEnumerator3                           = 8,
	NewEnumerator12                          = 9,
	NewEnumerator4                           = 10,
	NewEnumerator18                          = 11,
	NewEnumerator5                           = 12,
	NewEnumerator6                           = 13,
	NewEnumerator19                          = 14,
	NewEnumerator7                           = 15,
	NewEnumerator9                           = 16,
	NewEnumerator11                          = 17,
	EHNMenu_MAX                              = 18,
};

}

