#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EKeyEvents

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EKeyEvents.EKeyEvents
// NumValues: 0x0008
enum class EKeyEvents : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator6                           = 5,
	NewEnumerator3                           = 6,
	EKeyEvents_MAX                           = 7,
};

}

