#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EModScreen

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EModScreen.EModScreen
// NumValues: 0x0004
enum class EModScreen : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EModScreen_MAX                           = 3,
};

}

