#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HTML5Networking

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class HTML5Networking.WebSocketConnection
// 0x0010 (0x1900 - 0x18F0)
class UWebSocketConnection final : public UNetConnection
{
public:
	uint8                                         Pad_18F0[0x10];                                    // 0x18F0(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WebSocketConnection">();
	}
	static class UWebSocketConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWebSocketConnection>();
	}
};

// Class HTML5Networking.WebSocketNetDriver
// 0x0010 (0x0548 - 0x0538)
class UWebSocketNetDriver final : public UNetDriver
{
public:
	int32                                         WebSocketPort;                                     // 0x0538(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_53C[0xC];                                      // 0x053C(0x000C)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WebSocketNetDriver">();
	}
	static class UWebSocketNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWebSocketNetDriver>();
	}
};

}

