#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: LocStruct

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct LocStruct.LocStruct
// 0x0258 (0x0258 - 0x0000)
struct FLocStruct final
{
public:
	class FText                                   EN_2_F73F16554A8C358984F6E0B4D726062F;             // 0x0000(0x0018)(Edit, BlueprintVisible)
	class FText                                   RU_5_344376F249F62DD0F0267786090B3E06;             // 0x0018(0x0018)(Edit, BlueprintVisible)
	class FText                                   Turkish_39_2457A7184491003A7981B8A18E4FE273;       // 0x0030(0x0018)(Edit, BlueprintVisible)
	class FText                                   Swedish_40_EE6EC85C49C16BA792566B9136B09DC6;       // 0x0048(0x0018)(Edit, BlueprintVisible)
	class FText                                   Spanish_41_7C1935464D6322032A5DE3A18CB6CF47;       // 0x0060(0x0018)(Edit, BlueprintVisible)
	class FText                                   Slovak_42_75ADB8634CE3B669E580E0B14A595C6A;        // 0x0078(0x0018)(Edit, BlueprintVisible)
	class FText                                   PortugueseBrazil_43_A463841E49C2F603C4537094B55F74D0; // 0x0090(0x0018)(Edit, BlueprintVisible)
	class FText                                   Polish_44_440326C548337D9EB7CBF98F5EA23EED;        // 0x00A8(0x0018)(Edit, BlueprintVisible)
	class FText                                   Norwegian_45_AD4F85D94593273A4147D094BA6B6D62;     // 0x00C0(0x0018)(Edit, BlueprintVisible)
	class FText                                   Korean_46_253EA007403583DB09D9029307EEE991;        // 0x00D8(0x0018)(Edit, BlueprintVisible)
	class FText                                   Japanese_47_E32E2DCE4CC59650999F65B9274BF10F;      // 0x00F0(0x0018)(Edit, BlueprintVisible)
	class FText                                   Italian_48_B1FA6AFD4F38E62DF8C4968754AD40AA;       // 0x0108(0x0018)(Edit, BlueprintVisible)
	class FText                                   Hungarian_49_C18227694005A1F519A39FB6BA047867;     // 0x0120(0x0018)(Edit, BlueprintVisible)
	class FText                                   Hebrew_50_E22946AC4C4EF5CD151E79BA8E056282;        // 0x0138(0x0018)(Edit, BlueprintVisible)
	class FText                                   Greek_51_CBBCF0234792ADDDB32A79939D1BA75F;         // 0x0150(0x0018)(Edit, BlueprintVisible)
	class FText                                   French_52_0015191C4DB751B6BA94EAA61EF3D51C;        // 0x0168(0x0018)(Edit, BlueprintVisible)
	class FText                                   Finnish_53_074E7FC14129B1D4660178A123510D8F;       // 0x0180(0x0018)(Edit, BlueprintVisible)
	class FText                                   Dutch_55_AA4195C4439A9E6060F2158DD6A17428;         // 0x0198(0x0018)(Edit, BlueprintVisible)
	class FText                                   Danish_57_11AA0747418DA3F6E3F5EE86729EA4F2;        // 0x01B0(0x0018)(Edit, BlueprintVisible)
	class FText                                   Czech_59_3C188EB54A8CADB8BE4F428485F6414C;         // 0x01C8(0x0018)(Edit, BlueprintVisible)
	class FText                                   ChineseTraditional_61_921D35DA4C0C97B75E34F8849D263A17; // 0x01E0(0x0018)(Edit, BlueprintVisible)
	class FText                                   ChineseSimplified_67_366660E541E894E121AC278CA0CE4681; // 0x01F8(0x0018)(Edit, BlueprintVisible)
	class FText                                   German_68_9F5B4F4E4BC684D527B63199174F9EB4;        // 0x0210(0x0018)(Edit, BlueprintVisible)
	class FText                                   PortuguesePortugal_69_829BF6EC4BA454FDC2C982B1ADAFFE4F; // 0x0228(0x0018)(Edit, BlueprintVisible)
	class FText                                   Arabic_70_9D6CADD24C1A1C0E47CFEB9793D9C9D1;        // 0x0240(0x0018)(Edit, BlueprintVisible)
};

}

