#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MixerInteractivity

#include "Basic.hpp"


namespace SDK
{

// Enum MixerInteractivity.EMixerInteractivityParticipantState
// NumValues: 0x0004
enum class EMixerInteractivityParticipantState : uint8
{
	Joined                                   = 0,
	Input_Disabled                           = 1,
	Left                                     = 2,
	EMixerInteractivityParticipantState_MAX  = 3,
};

// ScriptStruct MixerInteractivity.MixerTransactionId
// 0x0010 (0x0010 - 0x0000)
struct FMixerTransactionId final
{
public:
	class FString                                 ID;                                                // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MixerInteractivity.MixerObjectReference
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FMixerObjectReference
{
public:
	class FName                                   Name;                                              // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MixerInteractivity.MixerStickReference
// 0x0000 (0x0008 - 0x0008)
struct FMixerStickReference final : public FMixerObjectReference
{
};

// ScriptStruct MixerInteractivity.MixerStickEventBinding
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FMixerStickEventBinding final
{
public:
	class FName                                   TargetFunctionName;                                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   StickId;                                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MixerInteractivity.MixerButtonReference
// 0x0000 (0x0008 - 0x0008)
struct FMixerButtonReference final : public FMixerObjectReference
{
};

// ScriptStruct MixerInteractivity.MixerButtonEventBinding
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FMixerButtonEventBinding final
{
public:
	class FName                                   TargetFunctionName;                                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ButtonId;                                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Pressed;                                           // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// ScriptStruct MixerInteractivity.MixerStickEventDynamicDelegateWrapper
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FMixerStickEventDynamicDelegateWrapper final
{
public:
	UMulticastDelegateProperty_                   Delegate;                                          // 0x0000(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
};

// ScriptStruct MixerInteractivity.MixerButtonEventDynamicDelegateWrapper
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FMixerButtonEventDynamicDelegateWrapper final
{
public:
	UMulticastDelegateProperty_                   PressedDelegate;                                   // 0x0000(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	UMulticastDelegateProperty_                   ReleasedDelegate;                                  // 0x0010(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
};

// ScriptStruct MixerInteractivity.MixerGroupReference
// 0x0000 (0x0008 - 0x0008)
struct FMixerGroupReference final : public FMixerObjectReference
{
};

// ScriptStruct MixerInteractivity.MixerSceneReference
// 0x0000 (0x0008 - 0x0008)
struct FMixerSceneReference final : public FMixerObjectReference
{
};

// ScriptStruct MixerInteractivity.MixerPredefinedGroup
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FMixerPredefinedGroup final
{
public:
	class FName                                   Name;                                              // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   InitialScene;                                      // 0x0008(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

