#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MixerInteractivity

#include "Basic.hpp"

#include "MixerInteractivity_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.CaptureSparkTransaction
// 0x0010 (0x0010 - 0x0000)
struct MixerInteractivityBlueprintLibrary_CaptureSparkTransaction final
{
public:
	struct FMixerTransactionId                    TransactionId;                                     // 0x0000(0x0010)(Parm, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetButtonDescription
// 0x0040 (0x0040 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetButtonDescription final
{
public:
	struct FMixerButtonReference                  Button;                                            // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	class FText                                   ButtonText;                                        // 0x0008(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
	class FText                                   HelpText;                                          // 0x0020(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
	int32                                         SparkCost;                                         // 0x0038(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetButtonState
// 0x0028 (0x0028 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetButtonState final
{
public:
	struct FMixerButtonReference                  Button;                                            // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	struct FTimespan                              RemainingCooldown;                                 // 0x0008(0x0008)(Parm, OutParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Progress;                                          // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DownCount;                                         // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PressCount;                                        // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         UpCount;                                           // 0x001C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Enabled;                                           // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	int32                                         ParticipantId;                                     // 0x0024(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetLoggedInUserInfo
// 0x0028 (0x0028 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetLoggedInUserInfo final
{
public:
	int32                                         UserId;                                            // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsLoggedIn;                                        // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	class FString                                 Name_0;                                            // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Level;                                             // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Experience;                                        // 0x001C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Sparks;                                            // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetName
// 0x0010 (0x0010 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetName final
{
public:
	struct FMixerObjectReference                  Obj;                                               // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	class FName                                   ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetParticipantsInGroup
// 0x0018 (0x0018 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetParticipantsInGroup final
{
public:
	struct FMixerGroupReference                   Group;                                             // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 ParticipantIds;                                    // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetRemoteParticipantInfo
// 0x0040 (0x0040 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetRemoteParticipantInfo final
{
public:
	int32                                         ParticipantId;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsParticipating;                                   // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	class FString                                 Name_0;                                            // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Level;                                             // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FMixerGroupReference                   Group;                                             // 0x0020(0x0008)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          InputEnabled;                                      // 0x0028(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FDateTime                              ConnectedAt;                                       // 0x0030(0x0008)(Parm, OutParm, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              LastInputAt;                                       // 0x0038(0x0008)(Parm, OutParm, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetStickDescription
// 0x0020 (0x0020 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetStickDescription final
{
public:
	struct FMixerStickReference                   Stick;                                             // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	class FText                                   HelpText;                                          // 0x0008(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.GetStickState
// 0x0018 (0x0018 - 0x0000)
struct MixerInteractivityBlueprintLibrary_GetStickState final
{
public:
	struct FMixerStickReference                   Stick;                                             // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	float                                         XAxis;                                             // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         YAxis;                                             // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Enabled;                                           // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	int32                                         ParticipantId;                                     // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.LoginSilently
// 0x0028 (0x0028 - 0x0000)
struct MixerInteractivityBlueprintLibrary_LoginSilently final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APlayerController*                      PlayerController;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLatentActionInfo                      LatentInfo;                                        // 0x0010(0x0018)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.MoveParticipantToGroup
// 0x0010 (0x0010 - 0x0000)
struct MixerInteractivityBlueprintLibrary_MoveParticipantToGroup final
{
public:
	struct FMixerGroupReference                   Group;                                             // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	int32                                         ParticipantId;                                     // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.SetCurrentScene
// 0x0010 (0x0010 - 0x0000)
struct MixerInteractivityBlueprintLibrary_SetCurrentScene final
{
public:
	struct FMixerSceneReference                   Scene;                                             // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	struct FMixerGroupReference                   Group;                                             // 0x0008(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.StartInteractivityLatent
// 0x0020 (0x0020 - 0x0000)
struct MixerInteractivityBlueprintLibrary_StartInteractivityLatent final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLatentActionInfo                      LatentInfo;                                        // 0x0008(0x0018)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.StopInteractivityLatent
// 0x0020 (0x0020 - 0x0000)
struct MixerInteractivityBlueprintLibrary_StopInteractivityLatent final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLatentActionInfo                      LatentInfo;                                        // 0x0008(0x0018)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function MixerInteractivity.MixerInteractivityBlueprintLibrary.TriggerButtonCooldown
// 0x0010 (0x0010 - 0x0000)
struct MixerInteractivityBlueprintLibrary_TriggerButtonCooldown final
{
public:
	struct FMixerButtonReference                  Button;                                            // 0x0000(0x0008)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	struct FTimespan                              CoolDown;                                          // 0x0008(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

