#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MixerInteractivity

#include "Basic.hpp"

#include "MixerInteractivity_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// Class MixerInteractivity.MixerInteractivityBlueprintEventSource
// 0x00F0 (0x0118 - 0x0028)
class UMixerInteractivityBlueprintEventSource final : public UObject
{
public:
	UMulticastDelegateProperty_                   ParticipantJoinedDelegate;                         // 0x0028(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	UMulticastDelegateProperty_                   ParticipantLeftDelegate;                           // 0x0038(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	UMulticastDelegateProperty_                   ParticipantInputDisabledDelegate;                  // 0x0048(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	UMulticastDelegateProperty_                   BroadcastingStartedDelegate;                       // 0x0058(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	UMulticastDelegateProperty_                   BroadcastingStoppedDelegate;                       // 0x0068(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	TMap<class FName, struct FMixerButtonEventDynamicDelegateWrapper> ButtonDelegates;               // 0x0078(0x0050)(ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPrivate)
	TMap<class FName, struct FMixerStickEventDynamicDelegateWrapper> StickDelegates;                 // 0x00C8(0x0050)(ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MixerInteractivityBlueprintEventSource">();
	}
	static class UMixerInteractivityBlueprintEventSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMixerInteractivityBlueprintEventSource>();
	}
};

// Class MixerInteractivity.MixerDelegateBinding
// 0x0048 (0x0070 - 0x0028)
class UMixerDelegateBinding final : public UDynamicBlueprintBinding
{
public:
	class FName                                   ParticipantJoinedBinding;                          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ParticipantLeftBinding;                            // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ParticipantInputDisabledBinding;                   // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BroadcastingStartedBinding;                        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BroadcastingStoppedBinding;                        // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FMixerButtonEventBinding>       ButtonEventBindings;                               // 0x0050(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TArray<struct FMixerStickEventBinding>        StickEventBindings;                                // 0x0060(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MixerDelegateBinding">();
	}
	static class UMixerDelegateBinding* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMixerDelegateBinding>();
	}
};

// Class MixerInteractivity.MixerInteractivityBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UMixerInteractivityBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void CaptureSparkTransaction(const struct FMixerTransactionId& TransactionId);
	static void GetButtonDescription(const struct FMixerButtonReference& Button, class FText* ButtonText, class FText* HelpText, int32* SparkCost);
	static void GetButtonState(const struct FMixerButtonReference& Button, struct FTimespan* RemainingCooldown, float* Progress, int32* DownCount, int32* PressCount, int32* UpCount, bool* Enabled, int32 ParticipantId);
	static void GetLoggedInUserInfo(int32* UserId, bool* IsLoggedIn, class FString* Name_0, int32* Level, int32* Experience, int32* Sparks);
	static class FName GetName(const struct FMixerObjectReference& Obj);
	static void GetParticipantsInGroup(const struct FMixerGroupReference& Group, TArray<int32>* ParticipantIds);
	static void GetRemoteParticipantInfo(int32 ParticipantId, bool* IsParticipating, class FString* Name_0, int32* Level, struct FMixerGroupReference* Group, bool* InputEnabled, struct FDateTime* ConnectedAt, struct FDateTime* LastInputAt);
	static void GetStickDescription(const struct FMixerStickReference& Stick, class FText* HelpText);
	static void GetStickState(const struct FMixerStickReference& Stick, float* XAxis, float* YAxis, bool* Enabled, int32 ParticipantId);
	static void LoginSilently(class UObject* WorldContextObject, class APlayerController* PlayerController, const struct FLatentActionInfo& LatentInfo);
	static void MoveParticipantToGroup(const struct FMixerGroupReference& Group, int32 ParticipantId);
	static void SetCurrentScene(const struct FMixerSceneReference& Scene, const struct FMixerGroupReference& Group);
	static void StartInteractivityLatent(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo);
	static void StartInteractivityNonLatent();
	static void StopInteractivityLatent(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo);
	static void StopInteractivityNonLatent();
	static void TriggerButtonCooldown(const struct FMixerButtonReference& Button, const struct FTimespan& CoolDown);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MixerInteractivityBlueprintLibrary">();
	}
	static class UMixerInteractivityBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMixerInteractivityBlueprintLibrary>();
	}
};

// Class MixerInteractivity.MixerInteractivitySettings
// 0x0088 (0x00B0 - 0x0028)
class UMixerInteractivitySettings final : public UObject
{
public:
	class FString                                 ClientId;                                          // 0x0028(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RedirectUri;                                       // 0x0038(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Sandbox;                                           // 0x0048(0x0010)(Edit, ZeroConstructor, Config, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 GameName;                                          // 0x0058(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GameVersionId;                                     // 0x0068(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	TArray<class FName>                           CachedButtons;                                     // 0x0070(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FName>                           CachedSticks;                                      // 0x0080(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FName>                           CachedScenes;                                      // 0x0090(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<struct FMixerPredefinedGroup>          DesignTimeGroups;                                  // 0x00A0(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MixerInteractivitySettings">();
	}
	static class UMixerInteractivitySettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMixerInteractivitySettings>();
	}
};

// Class MixerInteractivity.MixerInteractivityUserSettings
// 0x0020 (0x0048 - 0x0028)
class UMixerInteractivityUserSettings final : public UObject
{
public:
	class FString                                 RefreshToken;                                      // 0x0028(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 AccessToken;                                       // 0x0038(0x0010)(ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MixerInteractivityUserSettings">();
	}
	static class UMixerInteractivityUserSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMixerInteractivityUserSettings>();
	}
};

// Class MixerInteractivity.MixerLoginPane
// 0x0038 (0x0138 - 0x0100)
class UMixerLoginPane final : public UWidget
{
public:
	struct FColor                                 BackgroundColor;                                   // 0x0100(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AllowSilentLogin;                                  // 0x0104(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	UMulticastDelegateProperty_                   OnAuthCodeReady;                                   // 0x0108(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	UMulticastDelegateProperty_                   OnUIFlowFinished;                                  // 0x0118(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_128[0x10];                                     // 0x0128(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MixerLoginPane">();
	}
	static class UMixerLoginPane* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMixerLoginPane>();
	}
};

}

