#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Start

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// LinkerPlaceholderClass Start.PLACEHOLDER-CLASS__BP_WidgetStartMenu_C_0
// 0x0000 (0x0000 - 0x0000)
class UPLACEHOLDER_CLASS__BP_WidgetStartMenu_C_0 final
{
public:
};

// BlueprintGeneratedClass Start.Start_C
// 0x0050 (0x0380 - 0x0330)
class AStart_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(Transient, DuplicateTransient)
	class UBP_WidgetStartMenu_C*                  WidgetStartMenu;                                   // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHuman*                                 Player;                                            // 0x0340(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_348[0x8];                                      // 0x0348(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FTransform                             Transform;                                         // 0x0350(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Start(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Start_C">();
	}
	static class AStart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStart_C>();
	}
};

}

