#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UdpMessaging

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct UdpMessaging.UdpMockMessage
// 0x0010 (0x0010 - 0x0000)
struct FUdpMockMessage final
{
public:
	TArray<uint8>                                 Data;                                              // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};

}

